name: 静态内容部署

on:
  workflow_dispatch:  # 只允许手动触发

permissions:
  contents: write

jobs:
  # 简单的清理工作
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 提示信息
        run: |
          echo "静态内容部署工作流已被精简"
          echo "请使用deploy.yml工作流进行部署" 